apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
spec:
  profile: demo
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
